version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis
      - DEFAULT_REGION=eu-central-1
      - START_WEB=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "watchops"
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB: "watchops-db"
