{{- range $name, $cm := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lykon-service.fullname" $ }}-{{ $name }}
  labels:
    {{ include "fourkeys.labels" $ | indent 4 }}
data:
  {{ toYaml $cm | nindent 2 }}
{{- end }}
