{{- if and .Release.IsInstall .Values.pdb.enabled }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fourkeys.fullname" . }}
  labels:
{{ include "fourkeys.labels" . | indent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "fourkeys.selectorLabels" . | nindent 4 }}
{{- end }}
