{{- with .Values.app }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fourkeys.fullname" $ }}-app
  labels:
{{ include "fourkeys.labels" $ | indent 4 }}
type: Opaque
data:
  GITHUB_WEBHOOK_SECRET: {{ .config.githubSecret | b64enc | quote }}
  OPSGENIE_WEBHOOK_SECRET: {{ .config.opsgenieSecret | b64enc | quote }}
{{- end }}
{{- end }}

{{- range $name, $subscriber := .Values.subscribers }}
{{- with $subscriber }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fourkeys.fullname" $ }}-subscriber-{{ $name }}
  labels:
{{ include "fourkeys.labels" $ | indent 4 }}
type: Opaque
data:
  DATABASE_DSN: {{ .config.database.dsn | b64enc | quote }}
  {{- if eq .config.messageBroker.store.driver "postgres" }}
  MESSAGE_BROKER_KINESIS_STORE_POSTGRES_DSN: {{ .config.messageBroker.store.postgres.dsn | b64enc | quote }}
  {{- end }}
  {{- if eq .config.messageBroker.store.driver "mysql" }}
  MESSAGE_BROKER_KINESIS_STORE_MYSQL_DSN: {{ .config.messageBroker.store.mysql.dsn | b64enc | quote }}
  {{- end }}
  {{- if eq .config.messageBroker.store.driver "redis" }}
  MESSAGE_BROKER_KINESIS_STORE_REDIS_USERNAME: {{ .config.messageBroker.store.redis.username | b64enc | quote }}
  MESSAGE_BROKER_KINESIS_STORE_REDIS_PASSWORD: {{ .config.messageBroker.store.redis.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
