
{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "fourkeys.fullname" . }}
  labels:
{{ include "fourkeys.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fourkeys.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.serviceMonitor.port | default "http-probe" }}
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
