{{- if .Values.migrations.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "watchops.fullname" . }}-db-migrate
  labels:
{{ include "watchops.labels" . | indent 4 }}
{{- if .Values.migrations.labels }}
{{ toYaml .Values.migrations.labels | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: {{ template "watchops.fullname" . }}-db-migrate
{{- with $.Values.jobAnnotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
{{ include "watchops.labels" . | indent 8 }}
{{- if .Values.migrations.labels }}
{{ toYaml .Values.migrations.labels | indent 8 }}
{{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "watchops.fullname" . }}-db-migrate
          image: migrate/migrate:latest
          command: ['/migrate']
          args: ['-source', '{{ .Values.migrations.source }}', '-database', '{{ .Values.migrations.destination }}', '-verbose', 'up']
{{- end }}
