{{- range $name, $subscriber := .Values.subscribers }}
{{- if $subscriber.enabled }}
{{- with $subscriber }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "watchops.fullname" $ }}-subscriber-{{ $name }}
{{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels: {{- include "watchops.labels" $ | nindent 4 }}
    app.kubernetes.io/component: subscriber
{{- if .labels }}
{{ toYaml .labels | indent 4 }}
{{- end }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels: {{- include "watchops.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: subscriber
  strategy:
{{ toYaml .strategy | indent 4 }}
  template:
    metadata:
      name: {{ template "watchops.fullname" $ }}
{{- if .podAnnotations }}
      annotations:
{{ toYaml .podAnnotations | indent 8 }}
{{- end }}
      labels: {{- include "watchops.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: subscriber
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "watchops.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "watchops.fullname" $ }}-subscriber-{{ $name }}
            - secretRef:
                name: {{ template "watchops.fullname" $ }}-subscriber-{{ $name }}
          env:
            - name: KUBERNETES_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
          - name: http
            containerPort: {{ .port | default 8080 }}
            protocol: {{ .protocol | default "TCP" }}
          - name: http-probe
            containerPort: {{ .probePort | default 9090 }}
            protocol: {{ .probeProtocol | default "TCP" }}
        {{- if .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
        {{- end }}
        {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
        {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | indent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | indent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | indent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
