---
##########################
## Hadolint config file ##
##########################
ignored:
  - DL4001  # Ignore wget and curl in same file
  - DL4006  # ignore pipefail as we don't want to add layers
  - DL3018  # We do pin version in pipfile.lock
  - DL3013  # We do pin version in pipfile.lock
  - DL3003  # Ignore workdir so we don't add layers
  - DL3044  # Ignore using env in env
  - DL3008
  - DL3015
  - DL3009
  - DL3059
