version: '3'

services:
  pubsub:
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:316.0.0-emulators
      ports:
        - "8085:8085"
      entrypoint: gcloud beta emulators pubsub start --project watchops --host-port 0.0.0.0:8085
