{{- with .Values.publisher }}
{{- if .enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "watchops.fullname" $ }}-publisher
  labels:
{{ include "watchops.labels" $ | indent 4 }}
data:
  PORT: {{ .config.port | quote }}
  LOG_LEVEL: {{ .config.logLevel | quote }}
  REST_READ_TIMEOUT: {{ .config.rest.readTimeout | quote }}
  REST_WRITE_TIMEOUT: {{ .config.rest.writeTimeout | quote }}
  REST_IDLE_TIMEOUT: {{ .config.rest.idleTimeout | quote }}
  MESSAGE_BROKER_DRIVER: {{ .config.messageBroker.driver | quote }}
  MESSAGE_BROKER_KINESIS_TIMEOUT: {{ .config.messageBroker.kinesis.timeout | default "5s" | quote }}
  MESSAGE_BROKER_KINESIS_MAX_RETRIES: {{ .config.messageBroker.kinesis.maxRetries | default "3" | quote }}
  TOPIC_PREFIX: {{ .config.messageBroker.topicPrefix | quote }}
  SINGLE_TOPIC: {{ .config.messageBroker.singleTopic | quote }}
{{- end }}
{{- end }}
