{{- if .Values.networkPolicy.enabled }}
{{- if .Values.networkPolicy.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "watchops.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "watchops.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "watchops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: publisher
  ingress:
  - from:
    {{- if .Values.networkPolicy.ingress.namespaceSelector }}
    - namespaceSelector:
      {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 12 }}
    {{- else }}
    - namespaceSelector: {}
    {{- end }}
      {{- if .Values.networkPolicy.ingress.podSelector }}
      podSelector:
      {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 12 }}
      {{- end }}
    {{- end }}
    ports:
      - port: http
        protocol: TCP
{{- end }}
{{- if .Values.networkPolicy.alertmanager }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "watchops.name" . }}-egress-alertmanager
  labels:
    {{- include "watchops.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels: {{- include "watchops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: publisher
  egress:
    - ports:
        - port: {{ .Values.networkPolicy.alertmanager.port }}
          protocol: TCP
  {{- if .Values.networkPolicy.alertmanager.namespaceSelector }}
      to:
        - namespaceSelector:
          {{- toYaml .Values.networkPolicy.alertmanager.namespaceSelector | nindent 12 }}
          {{- if .Values.networkPolicy.alertmanager.podSelector }}
          podSelector:
          {{- toYaml .Values.networkPolicy.alertmanager.podSelector | nindent 12 }}
          {{- end }}
  {{- end }}
{{- end }}

