{{- with .Values.publisher }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "watchops.fullname" $ }}-publisher
  labels:
{{ include "watchops.labels" $ | indent 4 }}
type: Opaque
data:
  GITHUB_WEBHOOK_SECRET: {{ .config.githubSecret | b64enc | quote }}
  OPSGENIE_WEBHOOK_SECRET: {{ .config.opsgenieSecret | b64enc | quote }}
  PAGERDUTY_WEBHOOK_SECRET: {{ .config.pagerdutySecret | b64enc | quote }}
{{- end }}
{{- end }}
