openapi: 3.0.0
info:
  version: 0.1.2
  title: Four Keys
  description: The four keys project is responsible for aggregating information from our CI and ticketing systems to generate activity metrics. These metrics are used by us to improve our internal processes.
  contact:
    name: Italo Vietro
    url: 'https://github.com/italolelis'
    email: me@italovietro.com
servers:
  - url: 'https://{environment}.lykon.io/fourkeys'
    variables:
      environment:
        default: api.tools
paths:
  '/webhooks':
    post:
      summary: Received event data from a webhook from different sources (Github, Jira, and OpsGenie)
      operationId: incoming-webhook
      description: Receives event data from a webhook, checks if the source is authorized, checks if the signature is verified, and then sends the data to Kinesis.
      security:
        - GithubAPIKey: []
        - OpsGenieAPIKey: []
      responses:
        '200':
          description: The event data was queued successfully.
        '401':
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          $ref: "#/components/responses/InternalServerError"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              $ref: "./api/examples/github.json"
        description: 'The JSON body is a dynamic body coming from the source (Github, Jira, and OpsGenie). These data are defined in the provider documentation and should be checked there. It should not be null, use {} instead'
      tags:
        - Webhooks
components:
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
    InternalServerError:
      description: Internal Server Error
  securitySchemes:
    GithubAPIKey:
      type: apiKey
      in: header
      name: X-Hub-Signature
    OpsGenieAPIKey:
      type: apiKey
      in: header
      name: X-TOKEN
security:
  - GithubAPIKey: []
  - OpsGenieAPIKey: []
tags:
  - name: Fourkeys
    description: Fourkeys endpoints.
