name: Pull Request
on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_TERRAFORM_TERRASCAN: true
          VALIDATE_TERRAFORM_TFLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [lint]
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x
        
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/cache@v3.0.11
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.out
        fail_ci_if_error: true
        name: codecov-watchops
        verbose: true
